import pandas as pd
import numpy as np
df = pd.read_excel("messy_employee_data.xlsx")
df["Salary"] = df["Salary"].replace(",", "", regex=True).astype(float)
print("----------------ANALYZING OF DATA------------------------------\n")
print("--------Descriptive Statistics of Data---------")
print(df.describe(include="all"))
print("Number of Departments=",df["Department"].value_counts())
print("--------Check Missing Values--------")
print(df.isna().sum())
print("---------Unique Performance level--------")
print(df["Performance"].unique())
print("---------Salary of AI Department----------")
print(df[df["Department"]=="AI"]["Salary"].mean())
print("------Data of Employes Whose Salary greater than 70k--------")
print(df[df["Salary"]>70000])
print("-------Grouping of Data------------")
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Performance")["Age"].mean())
print("--------Sorting Of Data-----------")
print(df.sort_values("Salary",ascending=False).head(10))
print("-----------------Correlation of Age and Salary-------------------")
print(df[["Age","Salary"]].corr())
print("---------------------Outlier Analysis-----------------")
q1 = df["Salary"].quantile(0.25)
q3 = df["Salary"].quantile(0.75)
iqr = q3 - q1
outliers = df[(df["Salary"] < q1-1.5*iqr) | (df["Salary"] > q3+1.5*iqr)]
print(outliers)
print("-------------------------------------------------------------")
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Performance"] = df["Performance"].fillna(df["Performance"].mode()[0])
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])
df.drop_duplicates(inplace=True)
df.drop_duplicates(subset=["Name", "Age"], inplace=True)
salary_mean = np.mean(df["Salary"])
salary_std = np.std(df["Salary"])
lower_bound = salary_mean - (3 * salary_std)
upper_bound = salary_mean + (3 * salary_std)
df = df[(df["Salary"] >= lower_bound) & (df["Salary"] <= upper_bound)]
df.to_excel("Cleaned.xlsx", index=False)
print("Cleaning Done. File saved as Cleaned.xlsx")